### ISSUE TITLE
의문점

### ISSUE THREAD

**Issue by cy118** [team-cyhee/rabit_rest#7]
Optional<File> file = repository.findById(id);
        if (!file.isPresent()) {
            throw new NoSuchContentException(ContentType.FILE, id);
        }

 
    File file = repository.findById(id);
        if (file == null) {
            throw new NoSuchContentException(ContentType.FILE, id);
        }

후자를 쓰지않고 전자를 쓰는 이유?

**Comment by whgksdyd112** [comment]
Optional 이라는 걸 쓰는 이유는

예상치 못한 null로 인해서 NullPointerException이 발생하는것을 방지하기 위해성
null safe 하도록

**Comment by cy118** [comment]
@whgksdyd112  바부 나도 그건 아는데~
